### PR TITLE
updated styles to match Hack Club.

### PR DESCRIPTION
**Pull request by almonteluis**
I've reorganize the index file a bit and updated CSS to match Hack Code style guide better.  #1 @abbyfischler

### CODE REVIEW

**Comment by abbyfischler** [comment]
Please make the font Hack Club's font from the brand guide.

**Comment by almonteluis** [comment]
Okay I include the font-family to all links.

**Comment by abbyfischler** [comment]
Please have the buttons be Vertical. The whole point on this website is to be a play on link tree so we want it to be like it....

**Comment by almonteluis** [comment]
ok buttons are vertical. Anything else?

**Comment by almonteluis** [comment]
ok the button are now vertical

**Comment by abbyfischler** [comment]
@almonteluis Looks great. Thanks for doing that!

**Pull request merged**
